VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "IAppendableWordTable"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
'@Folder("eco_transferToWord.Core.Word.Table.Contracts")
Option Explicit

Public Sub AddRow()
End Sub

Public Property Get IsLastRowFilled() As Boolean
End Property

Public Sub AppendValue(ByVal Column As Long, ByVal Value As String, Optional ByVal isBold As Boolean)
End Sub



