VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "IAverageCalculator"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
'@Folder "eco_transferToWord.Core.Reference Values Validator.Average Calculator"
'@Interface
Option Explicit

Public Sub Append(ByVal Value As Double)
End Sub

Public Function GetAverage() As Double
End Function
