VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "IComparisonTableRowModel"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
'@Folder "eco_transferToWord.Core.Comparison Results Decoration.Comparison Block Decoration.Model"
'@Interface
Option Explicit

Public Property Get Number() As String
End Property

Public Property Get Name() As String
End Property

Public Property Get Value() As String
End Property

Public Property Get Uncertainty() As String
End Property

Public Property Get EnCriteria() As String
End Property

