VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "IComparisonDecorationService"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
'@Folder "eco_transferToWord.Core.Comparison Results Decoration"
'@Interface
Option Explicit

Public Sub DecorateComparisonResults()
End Sub

'Public Sub ExecuteFilling( _
'       ByVal ParticipantNumber As String, _
'       ByVal Templates As List_IFile_)
'End Sub
'
'Public Sub SaveChanges()
'End Sub


    
