VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "IComparisonChartsheetHandlerFac"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
'@Folder "eco_transferToWord.Core.Comparison Results Decoration.Comparison Block Decoration.Chart Sheet Handler"
'@Interface
Option Explicit

Public Function Create(ByVal Model As List_IOutputResultRowModel_) As IComparisonChartsheetHandler
End Function

