VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "IComparisonBlockDecoratorFactor"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
'@Folder "eco_transferToWord.Core.Comparison Results Decoration.Comparison Block Decoration"
'@Interface
Option Explicit

Public Function Create( _
       ByVal Strategy As IComparisonBlockStrategyFactory, _
       ByVal ParticipantTableTemplateFiles As List_IFile_) As IComparisonBlockDecorator
       
End Function


