VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "IComparisonDataBlockMapper"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
'@Folder("eco_transferToWord.Core.Initialization.Comparison Mapping.Block Data Mapper")
'@Interface
Option Explicit

Public Function GetComparisonResults() As List_IParticipantResult_
End Function
