VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "IComparisonBlockDecorator"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
'@Folder "eco_transferToWord.Core.Comparison Results Decoration.Comparison Block Decoration"
'@Interface
Option Explicit

Public Sub ExecuteFilling(ByVal ParticipantNumber As String, ByVal ComparisonBlockIndex As Long)
End Sub

Public Sub Dispose()
End Sub

Public Sub SaveChanges()
End Sub

