VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "IDecorationDocumentHandler"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
'@Folder "eco_transferToWord.Core.Comparison Results Decoration.Decoration Document Handler"
'@Interface
Option Explicit

Public Function GetDocument( _
       ByVal Strategy As IComparisonTemplateFileStrategy, _
       ByVal Files As List_IFile_) As IWordDocument
       
End Function


