VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "IDecorationTableHandler"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
'@Folder "eco_transferToWord.Core.Comparison Results Decoration.Decoration Table Handler"
'@Interface
Option Explicit

Public Function GetTable(Optional ByVal Index As Long = vbEmpty) As IWordTable
End Function

