VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "IEditableWordRange"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
'@Folder("eco_transferToWord.Core.Word.Range")
'@Interface
Option Explicit

Public Sub Copy()
End Sub

Public Sub PasteAndFormat()
End Sub

Public Sub PasteAsText(ByVal Text As String)
End Sub

Public Sub ClearContent()
End Sub
