VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "IExcelChart"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
'@Folder "eco_transferToWord.Core.Excel.Chart"
'@Interface
Option Explicit

Public Sub CopyAsPicture()
End Sub

Public Sub ApplyScale(ByVal MinValue As Double, ByVal MaxValue As Double)
End Sub
