VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "IExcelRange"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
'@Folder "eco_transferToWord.Core.Excel.Range"
'@Interface
Option Explicit

Public Property Get Value() As String
End Property

Public Property Let Value(ByVal RHS As String)
End Property

Public Sub Calculate()
End Sub
