VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "IExcelCellAddressParser"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
'@Folder "eco_transferToWord.Core.Reference Values Validator.Address Parser"
'@Interface
Option Explicit

Public Function GetRow() As Long
End Function

Public Function GetColumn() As Long
End Function
