VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "IExplorerFolderOpener"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
'@Folder "eco_transferToWord.Core.Results Presentator.Explorer Folder Open"
'@Interface
Option Explicit

Public Sub ShowInExplorer(ByVal folderPath As String)
End Sub

