VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "IFile"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
'@Folder("eco_transferToWord.Core.Initialization.File System Object.File")
'@Interface
Option Explicit

Public Property Get Path() As String
End Property

Public Property Get NameWithoutExtension() As String
End Property

