VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "IProgressServicePrimary"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
'@Folder "eco_transferToWord.Core.Progress Bar.Contracts"
'@Interface
Option Explicit

Public Function Initialize(ByVal TotalCount As Long) As IProgressService
End Function


