VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "IProgressService"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
'@Folder "eco_transferToWord.Core.Progress Bar.Contracts"
'@Interface
Option Explicit

Public Sub Show( _
       ByVal Message As String, _
       Optional ByVal Description As String = vbNullString)
    
End Sub


