VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "IReferenceValueValidationModel"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
'@Folder "eco_transferToWord.Core.Reference Values Validator.Model.Reference Value"
'@Interface
Option Explicit

Public Property Get Value() As String
End Property

Public Property Get Uncertainty() As String
End Property

Public Property Get ParticipantNames() As List_String_
End Property

