VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "ITemplatesMover"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
'@Folder "eco_transferToWord.Core.Preparation Document Templates.Templates Mover"
'@Interface
Option Explicit

Public Sub CopyTemplatesFolder(ByVal SourceFolderPath As String, ByVal DestinationFolderPath As String)
End Sub

