VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "ITransferMenuCacheHandler"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
'@Folder "eco_transferToWord.Core.Dialogs.Main Transfer.Cache Handler"
'@Interface
Option Explicit

Public Property Get Respondent() As String
End Property

Public Property Let Respondent(ByVal Value As String)
End Property

Public Property Get ControlObjectFactoryNumber() As String
End Property

Public Property Let ControlObjectFactoryNumber(ByVal Value As String)
End Property

Public Property Get SelectedSubcontract() As List_String_
End Property

Public Property Set SelectedSubcontract(ByVal Value As List_String_)
End Property

Public Sub Save()
End Sub

