VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "ITransferKey"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
'@Folder "eco_transferToWord.Core.Document IO.Transfer KeyValue.Key"
'@Interface
Option Explicit

Public Property Get Value() As String
Attribute Value.VB_UserMemId = 0
End Property
