VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "ITransferMenuParticipant"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
'@Folder "eco_transferToWord.Core.Initialization.Comparison Mapping.Model.Participant.Contracts"
'@Interface
Option Explicit

Public Property Get Number() As String
End Property

Public Property Get Tour() As String
End Property

Public Property Get TypeP() As String
End Property

Public Property Get Organisation() As String
End Property

