VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "ITransferResultsPresentator"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
'@Folder("eco_transferToWord.Core.Results Presentator")
'@Interface
Option Explicit

Public Sub OpenResultsFolder()
End Sub

Public Sub OpenTemporaryFolder()
End Sub
