VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "ITransferPreparationServiceFact"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
'@Folder "eco_transferToWord.Core.Preparation Document Templates"
'@Interface
Option Explicit

Public Function Create(ByVal Model As IExcelTransferModel) As ITransferPreparationService
End Function

