VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "IValuesRangeFillerFactory"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
'@Folder "eco_transferToWord.Core.Preparation Document Templates.Values Ranges Filler"
'@Interface
Option Explicit

Public Function Create( _
       ByVal ControlObjectFactoryNumber As String, _
       ByVal Participants As List_IParticipant_) As IParticipantValuesRangeFiller
       
End Function


