VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "IValueRounder"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
'@Folder "eco_transferToWord.Core.Initialization.Comparison Mapping.Block Data Mapper.Value Round"
'@Interface
Option Explicit

Public Function GetValue() As String
End Function

Public Function GetUncertainty() As String
End Function

Public Function GetRoundedToHundredths() As String
End Function

