VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "IValidatorInitialization"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
'@Folder("eco_transferToWord.Core.Initialization.Contracts")
'@Interface
Option Explicit

Public Property Get TemplateFilesCount() As Long
End Property

Public Property Get StaticValueFilesCount() As Long
End Property

Public Property Get SubctontractFilesCount() As Long
End Property

Public Property Get ComparisonAuxillaryFilesCount() As Long
End Property

Public Property Get ParticipantsCount() As Long
End Property

