VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "IWindowFinder"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
'@Folder "eco_transferToWord.Core.Results Presentator.Explorer Folder Open.Window Finder"
'@Interface
Option Explicit

Public Function GetWindow() As Object
End Function

Public Property Get IsWindowFinded() As Boolean
End Property

