VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "IWordDocument"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
'@Folder "eco_transferToWord.Core.Word.Document"
'@Interface
Option Explicit

Public Property Get ParentFolderPath() As String
End Property

Public Property Get Path() As String
End Property

Public Property Get Name() As String
End Property



